export const colors = {
  primary: '#1B4332',
  primaryLight: '#2D6A4F',
  primaryDark: '#081C15',
  secondary: '#D4AF37',
  secondaryLight: '#F0D78C',
  secondaryDark: '#B8960C',
  accent: '#40916C',
  background: '#F8F5F0',
  backgroundDark: '#0D1B14',
  surface: '#FFFFFF',
  surfaceDark: '#1A2E23',
  card: '#FFFFFF',
  cardDark: '#1E3A2F',
  text: '#1A1A1A',
  textDark: '#F0EDE8',
  textSecondary: '#6B6B6B',
  textSecondaryDark: '#A8A8A8',
  textArabic: '#1B4332',
  border: '#E8E0D4',
  borderDark: '#2D4A3A',
  error: '#C0392B',
  success: '#27AE60',
  warning: '#F39C12',
  info: '#3498DB',
  overlay: 'rgba(27, 67, 50, 0.85)',
  gradient: ['#1B4332', '#2D6A4F', '#40916C'],
  gradientGold: ['#B8960C', '#D4AF37', '#F0D78C'],
};

export const getTheme = (isDark) => ({
  colors: {
    primary: colors.primary,
    secondary: colors.secondary,
    accent: colors.accent,
    background: isDark ? colors.backgroundDark : colors.background,
    surface: isDark ? colors.surfaceDark : colors.surface,
    card: isDark ? colors.cardDark : colors.card,
    text: isDark ? colors.textDark : colors.text,
    textSecondary: isDark ? colors.textSecondaryDark : colors.textSecondary,
    textArabic: isDark ? colors.secondaryLight : colors.textArabic,
    border: isDark ? colors.borderDark : colors.border,
    error: colors.error,
    success: colors.success,
    warning: colors.warning,
    info: colors.info,
    overlay: colors.overlay,
    gradient: colors.gradient,
    gradientGold: colors.gradientGold,
  },
  isDark,
});
